---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-home-push
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgAwwakRtBpHBVRh+dTi7Dsznz3s8DLCF62r8++sX+y8A6lq6LCPXYUcYfnzfmJTneK4TrTJsXS4qFhuawLRgR4qxA//fYp3VvM8IAUDKG5kfVt1F/YzJM1UbX1GEAH8P9b7USuS9suAwF1f6X9b5sHhqvJ3XwjqBMuKLKO+4UnggMiVpaszRYSDkTONN8Sx58Fwebsgex7XHPbu0Phf2RfdzJm6aJ64IL5R3Z5PMcgHdPlkHXvC9YJ8xyTHT5RdjYscI0tygc2QcEHmLuNwDFVMVeKa8kdsWrEgFFR6Dn888mwnXYeV+nLUYPqWyjpd9t6HUs+TbLwQQi0YcmoMV1RQBqlkvU/00VduXjlErMSUv6DDGgdsDfSFow1uaKcRMx2Ru+WwEeYgwqj+4ZWTfs1SBUdrpIkVjHw5Y7quswCq57G3nO6dSPzlBit+KxNEfZfvzTr6hV/LEgcH9VCLqedFtp0GzS74uRboofTqOxWqdEFrvTjOEX+SqWV5bIm/w7XbvQwE6f8yKasXgsxDmPVLdUYWEosIz9M+lsLnoHuX/8jTqy7K/0nzYR28l/xg8pW8pxQqi/XW/+9t5LFTIUK1baVubuADrXbbPfdonAfhd2NplwTplau2i7p6kAJzKAte3MWoxBsO3JGXBdMW4YeNtjQunhCGmz6so0ZhlzZ1yDLRuhb/dW6D+AhIDoTEfYVd8Fg1+CAW98ncrgNLf+CORjscJOWVYWgmS5ZotegLODR+su7OQ9OWRmU/jTa0R6xkjT0NqxheDRRNF0vUITXucw2ylJ5TbasGWbJZS3q6ZlrrasajQIqjGR8y5y+e1krVMXJqbNQfikq35MY2sUYdFlQwBWHnpaJHfobDnmkhswefXrjS8S30L70uCgRrwvo1YkxTzaRevfDo7od0b9zg8e3ZsQ==
  template:
    metadata:
      name: registry-home-push
      namespace: ci
    type: kubernetes.io/dockerconfigjson
