---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-home-push
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgC5CHG3hEIPpvcYQBuN5JHDBgYk0kITF8D5Cvc3A7cR7AIJ+pO2q+Lc+WutUnsIOB7Kl1DsgtrrhQmjYLb6hYfonUps4qNyerdaYPxny5dAnOlFJ+WXlp3KDFgZzAAiLllkWnqrbJQbsi2df2btqdh13Oz9s+B782mo7qWOSdvo204V66MrsdwY2kNWe82WqyvtP7KK0hm3r9+fHkjxnglPlqxyDCCSzvZJeeT/dbEHMhtAYEH3sz+PRGjk/NiJvTeP0q8SbiXfDadur3mIUqUnxGBP8JHe44+f8QUn1MQ3H1167xRDwZbPeS+YqkhWA639ywRge6KfK+b1yHd5XAOcI5wZRH5AKNpQHnd+CDpUuiSamecwssc6E0BpBRg2MB1EHkKEcf/e33iPsQ13C1r1dbHHaQ8rPC2CEjZhqyPPZxa5xrEh4UkbnmAqE65Nq4TqzhRejxgkKkuNFm8wDDT/GEy72r8aemIYDUp7I8aq1dpzdWbzfqJ483pG9Wd8C89eYRrtePqlMevuQkKDc8gAhiapzrB1Z8eRbKkNsizZXotq6Gr+jhvcVCGQCd79PWY0ahwPkWoo/llfq8rhklcDAtwEAsu+by3PaUgLLB872HvDMLjfd3SnxqXX6StGft445Z4HeXAV/nCT9cGgPCavo08a4brD3TjVSt1Qprerx9AJMSVeMx8BZh6Istwf2iSrI+5it8y6wWd06mA3/cd5ANyGvIOpyesFdpw1SE7Kiezh5O7qcQGI2KdmoZuvv5f3iRo/IKsIxm5Qpj8f9PWfKNOs7ZV41A9x1WPAnPH3gTEUeVySL4ej8INQCGmZ985X9zzsyKt8i2O2
  template:
    metadata:
      name: registry-home-push
      namespace: ci
    type: kubernetes.io/dockerconfigjson
