---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demos
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 2m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-applications
  path: ./demos
  dependsOn:
    - name: traefik
