---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-applications
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/jabbas/flux-homeapps.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: internal-apps
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 2m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-applications
  path: ./internal-apps
  dependsOn:
    - name: traefik
    - name: authentik
