---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart:
    spec:
      chart: reflector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  interval: 1m0s
