---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: democratic-system
spec:
  chart:
    spec:
      chart: snapshot-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  interval: 1m0s
