---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-system
spec:
  chart:
    spec:
      chart: democratic-csi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  interval: 1m0s
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"
      fsGroupPolicy: ReadWriteOnceWithFSType

    driver:
      config:
        driver: zfs-generic-nfs
      nfs:
        shareStrategySetDatasetProperties:
          properties:
            sharenfs: "rw,no_subtree_check,no_root_squash"
      existingConfigSecret: csi-zfs-pve-ssd

    volumeSnapshotClasses:
      - name: democratic-csi
        deletionPolicy: Delete
        parameters: {}

    storageClasses:
      - name: zfs-nfs-csi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nolock
          - nfsvers=4.1
