---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-blueprints
  namespace: authentik
spec:
  chart:
    spec:
      chart: ./flux/infrastructure/authentik-blueprints/chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m0s
