apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprints
data:
  talos-oidc.yaml: |
    version: 1
    metadata:
      name: Talos OIDC Setup
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        id: talos-provider
        identifiers:
          name: Talos Cluster
        attrs:
          client_id: "talos-cluster-id"
          client_secret: !Env [AUTHENTIK_TALOS_SECRET, "files-fail-safe-secret"]
          client_type: confidential
          redirect_uris:
            - http://localhost:8000
            - http://localhost:18000
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-email]]
            - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-profile]]
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]

      - model: authentik_core.application
        identifiers:
          slug: talos-cluster
        attrs:
          name: Talos Kubernetes
          provider: !Find [authentik_providers_oauth2.oauth2provider, [id, talos-provider]]
          meta_launch_url: blank

      - model: authentik_core.group
        identifiers:
          name: kubernetes-admins
        attrs:
          is_superuser: false

      - model: authentik_providers_oauth2.scopemapping
        identifiers:
          name: Kubernetes Groups Mapping
        attrs:
          scope_name: groups
          description: "Map user groups to Kubernetes RBAC"
          expression: |
            return {
              "groups": [group.name for group in user.ak_groups.all()],
            }
