---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    size: 0.5Gi
  monitoring:
    enablePodMonitor: false
